// src/pages/Attendance.tsx
import SiteLayout from "@/components/site/SiteLayout";
import { PageHeader } from "@/components/site/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const Attendance = () => (
  <SiteLayout>
    <PageHeader
      eyebrow="Events"
      title="UAIS Event Attendance"
      description="If you are a registered member, use the email address associated with your membership. Otherwise, any email address works."
      accent="blue"
    />
    <section className="container pb-20">
      <form className="max-w-xl flex flex-col gap-3 sm:flex-row" action="https://api.uais.dev/attendance" method="post">
        <Input type="email" name="email" placeholder="email" required />
        <Button type="submit">Sign In</Button>
      </form>
    </section>
  </SiteLayout>
);

export default Attendance;

// src/pages/attendance.vue
<template lang="pug">
div
	section.section
		h1.title UAIS Event Attendance
		p
			| If you are a registered member then please use your email address associated
			| to your membership, otherwise please sign-in with any email address you like.
			| We won't send you newsletters but might send material from the event.
		form(
			action='https://api.uais.dev/attendance'
			method='post'
		)
			br
			.field.has-addons
				.control.has-icons-left
					input.input(
						type='email'
						name='email'
						placeholder='email'
						required='true'
					)
					span.icon.is-left
						fa(:icon='["fas", "envelope"]')
				.control
					input.button.is-info(
						type='submit'
						value='Sign In'
					)
</template>

<style lang="sass" scoped>
.field
	justfy-content: center
</style>

<script >
export default {
	head: {
		title: 'Event Attendees'
	}
}
</script>
